inherit_from: ./configs/Blue/blue.yaml
scene: data1

data:
  input_folder: data1
cam:
  H: 720 
  W: 1280 
  fx: 915.7
  fy: 515.08
  cx: 640.0
  cy: 360.0
  distortion: [0, 0, 0, 0, 0]

directions: ["front"] # ["front", "back", "left", "right"]
stride: 1            # use every X image from the dataset 
max_frames: 100       # use the first X images from the dataset, -1 means using all
