inherit_from: ./configs/LAC/lac.yaml
scene: data_collection_1

data:
  input_folder: data_collection_1
cam:
  H: 720 
  W: 1280 
  fx: 915.7
  fy: 515.08
  cx: 640.0
  cy: 360.0
  distortion: [0, 0, 0, 0, 0]
